version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: html-proofer
    versions:
    - 3.18.8
    - 3.19.0
  - dependency-name: pygments.rb
    versions:
    - 2.2.0
  - dependency-name: rake
    versions:
    - 13.0.3
  - dependency-name: nokogiri
    versions:
    - 1.11.2
  - dependency-name: jekyll-twitter-plugin
    versions:
    - 2.1.0
